const PDFDocument = require('pdfkit');

/**
 * Generates a C-Form PDF for a foreign national guest.
 * @param {Object} guest - The guest document
 * @param {Object} hotel - The hotel document
 * @returns {Promise<Buffer>} - Resolves with the PDF Buffer
 */
const generateCForm = (guest, hotel) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50, size: 'A4' });
      const buffers = [];
      
      doc.on('data', buffers.push.bind(buffers));
      doc.on('end', () => {
        const pdfData = Buffer.concat(buffers);
        resolve(pdfData);
      });
      doc.on('error', reject);

      // --- HEADER ---
      doc.fontSize(16).font('Helvetica-Bold').text('FORM C - INTIMATION BY HOTEL/LODGE/GUEST HOUSE', { align: 'center' });
      doc.fontSize(12).font('Helvetica').text('The Foreigners Act, 1946 (Rule 14)', { align: 'center' });
      doc.moveDown(1.5);

      const generatedDate = new Date().toLocaleDateString('en-IN');
      doc.fontSize(10).text(`Generated on: ${generatedDate}`, { align: 'right' });
      doc.moveDown(1);

      // --- HOTEL DETAILS SECTION ---
      doc.fontSize(12).font('Helvetica-Bold').text('1. HOTEL DETAILS', { underline: true });
      doc.moveDown(0.5);
      doc.font('Helvetica').fontSize(11);
      
      const hotelAddress = [hotel.address, hotel.city, hotel.state, hotel.pinCode].filter(Boolean).join(', ');
      
      doc.text(`Hotel Name: ${hotel.hotelName || 'N/A'}`);
      doc.text(`Hotel Address: ${hotelAddress || 'N/A'}`);
      doc.text(`Registration Date: ${generatedDate}`);
      doc.moveDown(1.5);

      // --- GUEST DETAILS SECTION ---
      doc.fontSize(12).font('Helvetica-Bold').text('2. GUEST DETAILS', { underline: true });
      doc.moveDown(0.5);
      doc.font('Helvetica').fontSize(11);

      const pg = guest.primaryGuest || {};
      const dobFormatted = pg.dob ? new Date(pg.dob).toLocaleDateString('en-IN') : 'N/A';
      const pAddress = pg.address 
        ? [pg.address.street, pg.address.city, pg.address.state, pg.address.zipCode].filter(Boolean).join(', ') 
        : 'N/A';

      doc.text(`Full Name: ${pg.name || 'N/A'}`);
      doc.text(`Date of Birth: ${dobFormatted}`);
      doc.text(`Gender: ${pg.gender || 'N/A'}`);
      doc.text(`Nationality: ${pg.nationality || 'N/A'}`);
      doc.text(`Passport/ID Type: ${guest.idType || 'N/A'}`);
      doc.text(`Passport/ID Number: ${guest.idNumber || 'N/A'}`);
      doc.text(`Permanent Address: ${pAddress}`);
      doc.moveDown(1.5);

      // --- STAY DETAILS SECTION ---
      doc.fontSize(12).font('Helvetica-Bold').text('3. STAY DETAILS', { underline: true });
      doc.moveDown(0.5);
      doc.font('Helvetica').fontSize(11);

      const sd = guest.stayDetails || {};
      const checkInFormatted = sd.checkIn ? new Date(sd.checkIn).toLocaleString('en-IN') : 'N/A';
      const checkoutFormatted = sd.expectedCheckout ? new Date(sd.expectedCheckout).toLocaleString('en-IN') : 'N/A';

      doc.text(`Room Number: ${sd.roomNumber || 'N/A'}`);
      doc.text(`Date of Arrival: ${checkInFormatted}`);
      doc.text(`Expected Date of Departure: ${checkoutFormatted}`);
      doc.text(`Purpose of Visit: ${sd.purposeOfVisit || 'N/A'}`);
      
      doc.moveDown(4);

      // --- FOOTER ---
      const pageBottom = doc.page.height - 100;
      doc.y = pageBottom;
      
      doc.fontSize(10).font('Helvetica-Oblique');
      doc.text('This form was auto-generated by Apna Manager Digital Compliance System', { align: 'center' });
      doc.text(`Guest Reference ID: ${guest.customerId}`, { align: 'center' });
      
      doc.moveDown(2);
      doc.font('Helvetica').fontSize(11);
      doc.text('Hotel authorized signature: ______________________', { align: 'left', continued: true });
      doc.text('Date of submission: ______________________', { align: 'right' });

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
};

module.exports = { generateCForm };
